version: '3.8'

services:
  automatic1111.v1.6:
    container_name: automatic1111-nvidia-docker
    image: piotrraszkowski/automatic1111-nvidia-docker:latest
    restart: always
    build:
      context: ./automatic1111/
      args:
        AUTOMATIC1111_VERSION: "v1.6.1"
    ports:
      - "7860:7860"
    environment:
      - USE_CUDA_118=true
      - USE_XFORMERS=true
      - IS_LOWVRAM=true
    volumes:
      - stable-diffusion-webui:/home/automatic1111/stable-diffusion-webui
    mem_reservation: "256M"
    mem_limit: "8G"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
  kohya_ss:
    container_name: kohya_ss-nvidia-docker
    image: piotrraszkowski/kohya_ss-nvidia-docker:latest
    restart: always
    build:
      context: ./kohya_ss/
    ports:
      - "7861:7860"
    volumes:
      - kohya_ss:/home/appuser/kohya_ss
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
  facefusion.v1:
    container_name: facefusion-nvidia-docker
    image: piotrraszkowski/facefusion-nvidia-docker:latest
    restart: always
    build:
      args:
        FACEFUSION_VERSION: "1.3.0"
      context: ./facefusion/
      dockerfile: Dockerfile
    ports:
      - "7862:7860"
    volumes:
      - facefusion.v2:/home/appuser/facefusion
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, video ]
  facefusion.v2:
    container_name: facefusion-nvidia-docker
    image: piotrraszkowski/facefusion-nvidia-docker:latest
    restart: always
    build:
      args:
        FACEFUSION_VERSION: "2.0.0"
      context: ./facefusion/
      dockerfile: facefusion/Dockerfile
    ports:
      - "7862:7860"
    volumes:
      - facefusion.v2:/home/appuser/facefusion
    mem_reservation: "256M"
    mem_limit: "8G"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, video ]

volumes:
  stable-diffusion-webui:
  kohya_ss:
  facefusion.v2:
