version: '3.8'

services:
  automatic1111-nvidia-docker:
    container_name: automatic1111-nvidia-docker
    image: piotrraszkowski/automatic1111-nvidia-docker:latest
    ports:
      - "7860:7860"
    environment:
      - IS_MACOS=true
    volumes:
      - stable-diffusion-webui:/home/automatic1111/stable-diffusion-webui

volumes:
  stable-diffusion-webui: