version: '3.8'

services:
  automatic1111-nvidia-docker:
    container_name: kohya_ss-nvidia-docker
    image: piotrraszkowski/kohya_ss-nvidia-docker:latest
    restart: always
    ports:
      - "7860:7860"
    environment:
#      - IS_MACOS=false
#      - USE_CUDA_121=true
#      - USE_XFORMERS=true
#      - CUDA_MODULE_LOADING=LAZY
    volumes:
      - kohya_ss:/home/kohya_ss/kohya_ss
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

volumes:
  kohya_ss: