version: '3.8'

services:
  automatic1111-nvidia-docker:
    container_name: kohya_ss-nvidia-docker
    image: piotrraszkowski/kohya_ss-nvidia-docker:latest
    ports:
      - "7860:7860"
    environment:
      - IS_MACOS=true
    volumes:
      - kohya_ss:/home/kohya_ss/kohya_ss

volumes:
  kohya_ss: